name: Publish Quick Play Maps By Sources

on:
  workflow_dispatch:
    inputs:
      sources:
        description: "Comma-separated list of source names to publish (e.g. DrDe,HOTB,ItSI)"
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Publish Quick Play Maps from Staging to Live
        run: npm run publish-quick-play-maps
        env:
          API_URL_LIVE: "https://www.dndbeyond.com/games/api"
          API_URL_STG: "https://stg.dndbeyond.com/games/api"
          BEARER_TOKEN_LIVE: "1234567890"
          BEARER_TOKEN_STG: "1234567890"
          SOURCES: ${{ inputs.sources }}
