name: Deploy Thumbnailer to Live

on:
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  S3_BUCKET_NAME: h7ktnb-dndbeyond-feywild-maps-live
  DD_ENV: live
  JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY_STG }}
  NODE_ENV: development
  STAGE: live
  MIN_LOG_LEVEL: warn

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.DDB_ADV_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.DDB_ADV_AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Serverless Deploy
        run: npm run deploy
