name: Deploy Thumbnailer to Staging

on:
  push:
    branches:
      - main
    paths:
      - "serverless.yml"
      - "handler.ts"
      - "src/**"
  workflow_dispatch:

env:
  AWS_REGION: us-east-2
  S3_BUCKET_NAME: h7ktnb-dndbeyond-feywild-maps-stg
  DD_ENV: staging
  JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY_STG }}
  NODE_ENV: development
  STAGE: stg
  MIN_LOG_LEVEL: debug

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.DDB_ADV_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.DDB_ADV_AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Serverless Deploy
        run: npm run deploy
